import Head from "next/head";
import Image from "next/image";
import { Abc } from "../components/Abc";
import { Creator } from "../components/Creator";
import { FontWeight } from "../components/FontWeight";
import { Footer } from "../components/Footer";
import { Header } from "../components/Header";
import { Intro } from "../components/Intro";
import { Tag } from "../components/Tag";
import { Tryit } from "../components/Tryit";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Tag />
      <Header />
      <Intro />
      <FontWeight />
      <Tryit />
      <Abc />

      <Creator />

      <Footer />
    </div>
  );
}
